"""empty message

Revision ID: 4521b545723d
Revises: d01c9bedbd67
Create Date: 2024-11-25 12:32:36.143600
aaa
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4521b545723d'
down_revision = 'd01c9bedbd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('local_id', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('consultation',
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mailadores', sa.String(length=50), nullable=True),
    sa.Column('local_id', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('consult_id')
    )
    op.create_table('local',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('local_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_table('notice',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('notice_title', sa.String(length=30), nullable=False),
    sa.Column('notice_text', sa.Text(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_extension', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('notice_reply',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=30), nullable=True),
    sa.Column('post_text', sa.String(length=200), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_extension', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('local_id', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('post_reply',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('users',
    sa.Column('local_id', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('mailaddress', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('post_reply')
    op.drop_table('post')
    op.drop_table('notice_reply')
    op.drop_table('notice')
    op.drop_table('local')
    op.drop_table('consultation')
    op.drop_table('calendar')
    # ### end Alembic commands ###
