"""empty message

Revision ID: 45c7311d93f1
Revises: 4c8869c4f2bb
Create Date: 2024-11-19 12:05:09.989261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c7311d93f1'
down_revision = '4c8869c4f2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mailadores', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('consult_id')
    )
    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               autoincrement=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    op.drop_table('consultation')
    # ### end Alembic commands ###
