"""empty message

Revision ID: 7f5a812e85ca
Revises: 4954f8fa45a3
Create Date: 2024-11-22 11:39:17.942724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5a812e85ca'
down_revision = '4954f8fa45a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_id', sa.String(length=3), nullable=False))

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_id', sa.String(length=3), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_id', sa.String(length=3), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('local_id')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('local_id')

    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_column('local_id')

    # ### end Alembic commands ###
