"""empty message

Revision ID: 7f906ff7001a
Revises: 45c7311d93f1
Create Date: 2024-11-19 14:02:53.016113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f906ff7001a'
down_revision = '45c7311d93f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    # ### end Alembic commands ###
