"""empty message

Revision ID: 974785f25f9d
Revises: d7551955ac00
Create Date: 2024-11-19 10:41:03.082865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '974785f25f9d'
down_revision = 'd7551955ac00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
