"""empty message

Revision ID: bb2a3bf54c3d
Revises: 08a8c1063355
Create Date: 2024-11-20 10:25:31.878842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2a3bf54c3d'
down_revision = '08a8c1063355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notice_title', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('image_extension', sa.String(length=10), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('image_extension')
        batch_op.drop_column('notice_title')

    # ### end Alembic commands ###
