"""empty message

Revision ID: dda7a919bbfe
Revises: 7f5a812e85ca
Create Date: 2024-11-22 11:42:03.970489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda7a919bbfe'
down_revision = '7f5a812e85ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_id', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('local_id')

    # ### end Alembic commands ###
