"""empty message

Revision ID: e0db6c71c02a
Revises: dae2df55fcd4
Create Date: 2024-11-22 11:32:27.155517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0db6c71c02a'
down_revision = 'dae2df55fcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="tag::integer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
